In [1]:
"""
Tensorflow v1.0.0 で　XOR を解く
"""

import tensorflow as tf
import numpy as np

# make data here

# Rowはデータ、Columnは二つの入力
data = np.array([
        [0,0],
        [0,1],
        [1,0],
        [1,1],
    ])

# Rowはラベル
labels = np.array([
        [0],
        [1],
        [1],
        [0],
    ])
# 例えば、一行目のデータ[0,0]　ー＞　一行目のラベル[0]
#              二行目のデータ[0,1]　ー＞　二行目のラベル[1]

# 今回は、データが四つしかないので、train組みとtest組みを一緒にする
# 本番は、train組みとtest組み分けないと行けない
train_data = data
train_labels = labels
test_data = data
test_labels = labels


In [2]:
# neural net shape is 2 x 4 x 1

#二つの入力、一つの出力、隠れ層は四つのニューロン
input_dim = data.shape[1]
hidden_dim = 4
output_dim = labels.shape[1]

In [3]:

# Define neural net here

#入力データとラベルの変数を定義し、x　と y_　とする  
# 次元：　Noneはデータの量、今回４だけど、Noneを入れて、自動やってくれる
x = tf.placeholder(tf.float32, [None, input_dim])
y_ = tf.placeholder(tf.float32, [None, output_dim])

# 左のsynapesの方程式を定義し、乱数で初期化
w1 = tf.Variable(tf.random_uniform([input_dim, hidden_dim], minval=-0.9, maxval=0.9))
b1 = tf.Variable(tf.random_uniform([hidden_dim], minval=-0.9, maxval=0.9))

# 隱れ層は、sigmoid (logits)の方程式で定義する
hidden_layer = tf.sigmoid(tf.matmul(x, w1) + b1)

# 右のsynapesの方程式を定義し、乱数で初期化
w2 = tf.Variable(tf.random_uniform([hidden_dim, output_dim], minval=-0.9, maxval=0.9))
b2 = tf.Variable(tf.random_uniform([output_dim], minval=-0.9, maxval=0.9))

# 出力 y も、sigmoid (logits)の方程式で定義する
y = tf.sigmoid(tf.matmul(hidden_layer, w2) + b2)




In [4]:
# Define cost function and train step here

# コースド算数、
#mean_sq_error = tf.reduce_mean(tf.reduce_sum(0.5 * tf.square(y - y_), reduction_indices=[1]))
#cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))
cross_entropy = tf.reduce_mean(- y_ * tf.log(y) - (1.0-y_) * tf.log(1.0-y))

# 普通のGradient Descentを使い、cross_entropyを最小化することを宣言する
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy)

#  出力　y　と　ラベル　y_　あってるかを確認する関数を定義
correct_prediction = tf.equal(tf.round(y), tf.round(y_))

# accuracy = あってるデータ個数　/ 全データ個数
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [5]:
# training session here

sess = tf.Session()
sess.run(tf.global_variables_initializer())

# training は、4000 回を繰り返す
for i in range(4000):
    _, ce, prediction = sess.run([train_step, cross_entropy, tf.round(y)], feed_dict={x: train_data, y_: train_labels})
    if (i%100)==0:
        print('Iteration: ', i)
        print('予測: ')
        print('    ', prediction)
        print('誤差= ', ce)
        print()


Iteration:  0
予測: 
     [[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
誤差=  0.723827

Iteration:  100
予測: 
     [[ 0.]
 [ 0.]
 [ 1.]
 [ 1.]]
誤差=  0.695816

Iteration:  200
予測: 
     [[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]
誤差=  0.694941

Iteration:  300
予測: 
     [[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]
誤差=  0.694179

Iteration:  400
予測: 
     [[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]]
誤差=  0.693487

Iteration:  500
予測: 
     [[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]]
誤差=  0.69283

Iteration:  600
予測: 
     [[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]]
誤差=  0.692177

Iteration:  700
予測: 
     [[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]]
誤差=  0.691499

Iteration:  800
予測: 
     [[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]]
誤差=  0.690767

Iteration:  900
予測: 
     [[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]]
誤差=  0.689952

Iteration:  1000
予測: 
     [[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]]
誤差=  0.689018

Iteration:  1100
予測: 
     [[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]]
誤差=  0.687927

Iteration:  1200
予測: 
     [[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]]
誤差=  0.686634

Iteration:  1300
予測: 
     [[ 0.]
 [ 1.]
 [ 0.]
 [ 1.]]
誤差=  0.685084

Iteration:  1400
予測